import { mutation } from './_generated/server'

const SEED_RECIPES = [
  // Existing favorites
  {
    link: 'https://immigrantstable.com/baked-harissa-salmon/',
    name: 'Baked harissa salmon',
    cuisine: 'North African',
    isFavorite: true,
    ingredients: ['Salmon', 'Rice'],
  },
  {
    link: 'https://tiffycooks.com/beef-and-broccoli-noodles/',
    name: 'Beef and broccoli noodles',
    cuisine: 'Chinese',
    isFavorite: true,
    ingredients: ['Beef', 'Noodles', 'Add shiitake mushrooms'],
    notes: 'Add shiitake mushrooms',
  },
  {
    link: '',
    name: 'Bok choy and lap cheung fried rice',
    cuisine: 'Chinese',
    isFavorite: true,
    ingredients: ['Lap cheung', 'Rice', 'Bok choy', 'Corn', 'Garlic', 'Ginger'],
    notes: 'Sauce: dark soy sauce, oyster sauce, white pepper',
  },
  {
    link: '',
    name: 'Burmese noodle salad',
    cuisine: 'Burmese',
    isFavorite: true,
    ingredients: [
      'Fishcake, egg',
      'Noodles',
      'Hokkien noodles',
      'Boiled eggs x6',
      'Boiled potatoes (just tender) x4 with tumeric and paprika',
      'Fishcake',
      'Lettuce',
    ],
  },
  {
    link: 'https://www.eatingwell.com/creamy-pesto-shrimp-with-gnocchi-peas-8598661',
    name: 'Creamy pesto shrimp with gnocchi peas',
    cuisine: 'Italian',
    isFavorite: true,
    ingredients: ['Shrimp', 'Gnocchi'],
  },
  {
    link: 'https://www.janicefung.com/chinese-cucumber-salad-recipe/',
    name: 'Cucumber salad',
    cuisine: 'Chinese',
    isFavorite: true,
    ingredients: [],
  },
  {
    link: '',
    name: 'Garlic butter basa fish',
    cuisine: 'Vietnamese',
    isFavorite: true,
    ingredients: ['Fish', 'Potatoes'],
  },
  {
    link: 'https://www.foodandwine.com/recipes/garlic-butter-steak-bites',
    name: 'Garlic butter steak bites',
    cuisine: 'American',
    isFavorite: true,
    ingredients: ['Beef', 'Potatoes'],
  },
  {
    link: 'https://www.instagram.com/reel/DLLZXFmxIGE/?igsh=M2ZwNzU2ZHFqeTJy',
    name: 'Garlic prawn pasta',
    cuisine: 'Italian',
    isFavorite: true,
    ingredients: [
      'Prawns',
      'Pasta',
      '8-10 large shrimp (peeled and deveined seasoned with 1/4 tsp salt, 1/4 tsp smoked paprika, 1 tbsp olive oil)',
      '100g pasta (spaghetti, linguine, or angel hair)',
      '3-4 garlic cloves, finely chopped',
      '1/4 tsp red pepper flakes (optional)',
    ],
    notes:
      '2 tbsp unsalted butter, zest of 1/2 lemon, 1 tbsp lemon juice, 1/4 cup dry white wine or chicken broth, 2 tbsp chopped parsley, 2 tbsp grated parmesan',
  },
  {
    link: 'https://eatwithclarity.com/greek-chicken-bowls/',
    name: 'Greek chicken bowls',
    cuisine: 'Greek',
    isFavorite: true,
    ingredients: ['Chicken', 'Rice'],
  },
  {
    link: 'https://www.donnahay.com.au/recipes/dinner/pizza/harissa-and-smoked-paprika-beef-mince-flatbread',
    name: 'Harissa & smoked paprika beef mince flatbread',
    cuisine: 'Middle Eastern',
    isFavorite: true,
    ingredients: ['Beef', 'Flatbread'],
  },
  {
    link: 'https://www.lastingredient.com/mushroom-corn-penne/',
    name: 'Mushroom corn penne',
    cuisine: 'Italian',
    isFavorite: true,
    ingredients: ['Chorizo', 'Pasta', 'Add chorizo, Alfredo sauce'],
    notes: 'Add chorizo, Alfredo sauce',
  },
  {
    link: 'https://www.deliciousmagazine.co.uk/recipes/cheese-bacon-pesto-puffs/',
    name: 'Open face pastries - mix toppings',
    cuisine: 'Scandinavian',
    isFavorite: true,
    ingredients: [
      'Pastry',
      'Tomato paste',
      'Cheddar/mozzarella',
      'Chorizo, ham',
      'Mushrooms',
      'Spinach',
    ],
    notes: 'Cherry tomatoes, pineapple, egg wash',
  },
  {
    link: 'https://www.eatingwell.com/high-protein-pasta-salad-11712920',
    name: 'Pasta salad',
    cuisine: 'Mediterranean',
    isFavorite: true,
    ingredients: [
      'Tuna',
      'Pasta',
      'Tuna x3 95g',
      'Cherry tomatoes',
      'Cucumber',
      'Bocconcini',
    ],
    notes:
      'Sauce: 1/4 cup oil, 3 tbsps lemon juice, 3 tsps Moroccan spice, 3 tsps italian herbs, 1 tsp thyme, salt, pepper. Optional: sundried tomatoes, roasted capsicum',
  },
  {
    link: 'https://www.marionskitchen.com/15-minute-pork-sesame-udon-noodles/',
    name: 'Pork sesame udon noodles',
    cuisine: 'Japanese',
    isFavorite: true,
    ingredients: ['Pork', 'Noodles'],
  },
  {
    link: 'https://www.recipetineats.com/mushroom-sauce/',
    name: 'Steak and potatoes with mushroom sauce',
    cuisine: 'French',
    isFavorite: true,
    ingredients: ['Beef', 'Potatoes'],
  },
  {
    link: 'https://moribyan.com/sushi-bake/',
    name: 'Sushi bake',
    cuisine: 'Japanese',
    isFavorite: true,
    ingredients: ['Crab', 'Rice'],
  },
  {
    link: 'https://www.recipetineats.com/teriyaki-beef-bowls/',
    name: 'Teriyaki beef bowls',
    cuisine: 'Japanese',
    isFavorite: true,
    ingredients: ['Rice', 'Carrots', 'Zucchini', 'Brown onion', 'Beef mince'],
    notes: '4 cloves garlic, teriyaki sauce: soy, mirin, sugar',
  },
  {
    link: '',
    name: 'Udon and lap cheung stir fry',
    cuisine: 'Asian Fusion',
    isFavorite: true,
    ingredients: [
      'Lap cheung',
      'Noodles',
      'Udon noodles',
      'Lap Cheung',
      'Frozen peas & corn',
      'Spring onions',
      'Garlic',
    ],
    notes: 'Sauce: soy sauce, dark soy sauce, oyster sauce',
  },
  {
    link: 'https://www.delicious.com.au/recipes/zucchini-pesto-pasta-recipe/ctfpj6at',
    name: 'Zucchini pesto pasta',
    cuisine: 'Italian',
    isFavorite: true,
    ingredients: ['Shrimp', 'Pasta', 'Add paprika prawns'],
    notes: 'Add paprika prawns',
  },
  // New recipes from CSV
  {
    link: 'https://www.marionskitchen.com/15-minute-garlic-prawn-udon/',
    name: 'Garlic prawn udon',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Prawns', 'Udon noodles'],
  },
  {
    link: 'https://m.youtube.com/watch?v=17F0IVT4zO0&list=WL&index=13',
    name: 'Chocolate lava cake bowl',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Chocolate'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/7906693/20-minute-balsamic-mushroom-spinach-pasta/',
    name: 'Balsamic mushroom pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta', 'Mushrooms', 'Spinach', 'Chorizo'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/asian-style-soy-and-sesame-fish-bites',
    name: 'Soy sesame fish bites',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Fish'],
  },
  {
    link: 'https://www.delicious.com.au/recipes/baked-field-mushrooms-breadcrumbs-garlic-thyme-recipe/1hv6maa9',
    name: 'Baked field mushrooms',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Mushrooms', 'Breadcrumbs', 'Garlic', 'Thyme'],
    notes: 'Apple cider vinegar instead of white wine',
  },
  {
    link: 'https://www.eatingwell.com/recipe/263566/baked-fish-tacos-with-avocado/',
    name: 'Baked fish tacos',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Fish', 'Avocado'],
  },
  {
    link: 'https://www.foodnetwork.com/recipes/giada-de-laurentiis/baked-rigatoni-with-sausage-5545399',
    name: 'Baked rigatoni with sausage',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Rigatoni', 'Sausage'],
  },
  {
    link: 'https://www.youtube.com/watch?v=qbZRqjGQ82g&list=WL&index=7',
    name: 'Baked sushi',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Tuna', 'Crab', 'Rice'],
  },
  {
    link: 'https://www.thekitchn.com/easy-baked-ziti-22971260',
    name: 'Baked ziti',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Ziti', 'Cheese'],
  },
  {
    link: 'https://cafedelites.com/banana-bread/',
    name: 'Banana choc chip bread',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Banana', 'Chocolate chips'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/barramundi-fish-cakes',
    name: 'Barramundi fish cakes',
    cuisine: 'Australian',
    isFavorite: false,
    ingredients: ['Barramundi'],
  },
  {
    link: 'https://www.bonappetit.com/recipe/basic-bulgogi',
    name: 'Bulgogi',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Beef'],
  },
  {
    link: 'https://www.donnahay.com.au/recipes/dinner/beef-and-broccolini-in-oyster-sauce-stir-fry',
    name: 'Beef broccolini stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef', 'Broccolini'],
  },
  {
    link: 'https://www.slimmingeats.com/blog/beef-and-potato-curry',
    name: 'Beef potato curry',
    cuisine: 'Indian',
    isFavorite: false,
    ingredients: ['Beef', 'Potatoes'],
    notes: 'Ground cumin',
  },
  {
    link: 'https://eatinginaninstant.com/instant-pot-beef-and-shells/',
    name: 'Beef and shells',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Beef', 'Pasta shells'],
  },
  {
    link: 'https://www.youtube.com/watch?v=WIvDzUqRPFU',
    name: 'Beef veg pastries',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Beef', 'Pastry'],
    notes: 'Crushed tomatoes',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/beef-burgers-with-caramelised-pineapple',
    name: 'Beef pineapple burgers',
    cuisine: 'Australian',
    isFavorite: false,
    ingredients: ['Beef', 'Pineapple', 'Spinach', 'Tomato'],
    notes: 'Coriander',
  },
  {
    link: '',
    name: 'Beef chilli oil noodles',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef', 'Noodles', 'Carrot'],
  },
  {
    link: 'https://redhousespice.com/beef-chow-fun/',
    name: 'Beef chow fun',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef', 'Rice noodles', 'Choy sum'],
  },
  {
    link: 'https://www.marionskitchen.com/beef-mushroom-ginger-stir-fry/',
    name: 'Beef mushroom ginger stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef', 'Mushrooms', 'Ginger'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/249546/beer-battered-fish-tacos-with-tomato-avocado-salsa/',
    name: 'Beer battered fish tacos',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Fish', 'Avocado', 'Tomato'],
  },
  {
    link: 'https://www.deliciousmagazine.co.uk/recipes/bolognese-quesadilla/',
    name: 'Bolognese quesadillas',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Beef mince', 'Tortillas'],
    notes: 'Add mince',
  },
  {
    link: 'https://www.donnahay.com.au/recipes/dinner/brisket-ragu-with-mushrooms-and-parmesan-mash',
    name: 'Brisket with mushroom ragu',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Brisket', 'Mushrooms', 'Potatoes'],
  },
  {
    link: 'https://www.bonappetit.com/recipe/broccoli-and-egg-fried-rice',
    name: 'Broccoli egg fried rice',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Broccoli', 'Eggs', 'Rice'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/256290/broccoli-casserole/',
    name: 'Broccoli casserole',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Broccoli'],
  },
  {
    link: 'https://www.taste.com.au/recipes/broccoli-corn-haloumi-fritters-recipe/8ushgo3n',
    name: 'Broccoli halloumi fritters',
    cuisine: 'Mediterranean',
    isFavorite: false,
    ingredients: ['Broccoli', 'Corn', 'Halloumi'],
  },
  {
    link: 'https://www.eatingwell.com/broccoli-melts-8732907',
    name: 'Broccoli melts',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Broccoli', 'Bread'],
    notes: 'Broccoli mix: oil, garlic, Italian seasoning and chilli flakes, lemon zest, salt. Sandwich press',
  },
  {
    link: 'https://m.youtube.com/watch?v=l1nnao6cwEI&list=WL&index=11',
    name: 'Cajun shrimp pasta',
    cuisine: 'Cajun',
    isFavorite: false,
    ingredients: ['Shrimp', 'Pasta'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/carrot-mac-and-cheese-bites',
    name: 'Carrot mac cheese bake',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Carrot', 'Pasta', 'Spinach', 'Bacon'],
  },
  {
    link: 'https://www.marionskitchen.com/char-kway-teow/',
    name: 'Char kway teow',
    cuisine: 'Malaysian',
    isFavorite: false,
    ingredients: ['Rice noodles', 'Prawns'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/chargrilled-haloumi-and-corn-tacos',
    name: 'Halloumi corn tacos',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Halloumi', 'Corn'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/cheats-tuna-and-pea-pasta-bake',
    name: 'Tuna pea pasta bake',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Tuna', 'Peas', 'Pasta'],
  },
  {
    link: 'https://www.deliciousmagazine.co.uk/recipes/cheese-bacon-pesto-puffs/',
    name: 'Cheese bacon pesto tarts',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Cheese', 'Bacon', 'Pesto', 'Pastry'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/cheesy-bacon-and-spinach-macaroni',
    name: 'Cheesy bacon spinach mac',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Bacon', 'Spinach', 'Macaroni'],
  },
  {
    link: 'https://www.epicurious.com/recipes/food/views/cheesy-chicken-enchilada-skillet',
    name: 'Chicken enchilada skillet',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Chicken', 'Cheese'],
  },
  {
    link: 'https://www.marionskitchen.com/cheesy-miso-tuna-mornay/',
    name: 'Miso tuna mornay',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Tuna', 'Cheese'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/cheesy-pasta-and-basil-bake',
    name: 'Cheesy basil pasta bake',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta', 'Chicken', 'Basil'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/267768/chicken-spinach-skillet-pasta-with-lemon-parmesan/',
    name: 'Lemon chicken spinach pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Spinach', 'Pasta', 'Lemon'],
  },
  {
    link: 'https://tasty.co/article/hannahmars/easy-fettuccine',
    name: 'Chicken bacon florentine',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Bacon', 'Fettuccine'],
  },
  {
    link: 'https://www.bhg.com.au/chicken-bacon-pea-and-mint-spaghetti',
    name: 'Chicken bacon pea pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Bacon', 'Peas', 'Mint', 'Spaghetti'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/chicken-banh-mi',
    name: 'Chicken banh mi',
    cuisine: 'Vietnamese',
    isFavorite: false,
    ingredients: ['Chicken'],
  },
  {
    link: 'https://tasty.co/recipe/chicken-bibimbap',
    name: 'Chicken bibimbap',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Chicken', 'Rice', 'Vegetables'],
  },
  {
    link: '',
    name: 'Chicken snack wraps',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Chicken'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/chicken-stroganoff-bake',
    name: 'Chicken stroganoff bake',
    cuisine: 'Russian',
    isFavorite: false,
    ingredients: ['Chicken', 'Cherry tomatoes'],
  },
  {
    link: '',
    name: 'Chicken teriyaki noodles',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Chicken', 'Hokkien noodles', 'Bok choy', 'Spring onions', 'Mushrooms', 'Carrot'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/chilli-honey-prawn-and-lap-cheong-pizza',
    name: 'Honey prawn lap cheong pizza',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Prawns', 'Lap cheong', 'Honey'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/chilli-pork-and-bean-stir-fry',
    name: 'Chilli pork bean stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Pork', 'Beans'],
  },
  {
    link: 'https://www.smh.com.au/goodfood/recipes/10-minute-chilli-prawn-and-corn-pasta-20240205-p5f2kp.html',
    name: 'Chilli prawn corn pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Prawns', 'Corn', 'Pasta'],
  },
  {
    link: 'https://www.donnahay.com.au/recipes/dinner/pasta-and-noodles/chilli-tuna-lemon-and-dill-pasta',
    name: 'Chilli tuna dill pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Tuna', 'Lemon', 'Dill', 'Pasta'],
  },
  {
    link: 'https://www.marionskitchen.com/chinese-egg-drop-chicken-soup/',
    name: 'Egg drop chicken soup',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Chicken', 'Eggs'],
    notes: 'Small bag of spinach to lightly cook and eat this week',
  },
  {
    link: 'https://www.marionskitchen.com/chinese-sausage-egg-fried-rice/',
    name: 'Chinese sausage fried rice',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Chinese sausage', 'Eggs', 'Rice'],
  },
  {
    link: 'https://cooking.nytimes.com/recipes/1023678-chocolate-hazelnut-cookies',
    name: 'Chocolate hazelnut cookies',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Chocolate', 'Hazelnuts'],
  },
  {
    link: 'https://www.hellofresh.com.au/recipes/Easy-Chorizo-&-Semi-Dried-Tomato-Pasta-651a0b26bbf22188bdeceb9a',
    name: 'Chorizo sundried tomato pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chorizo', 'Pasta', 'Sundried tomatoes'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/chorizo-and-prawn-skewers-with-lemon-aioli',
    name: 'Chorizo prawn skewers',
    cuisine: 'Spanish',
    isFavorite: false,
    ingredients: ['Chorizo', 'Prawns'],
  },
  {
    link: 'https://www.marionskitchen.com/quick-chorizo-beef-tacos/',
    name: 'Chorizo beef tacos',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Chorizo', 'Beef', 'Spinach'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/chorizo-fajitas-tacos',
    name: 'Chorizo fajitas',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Chorizo'],
  },
  {
    link: 'https://www.budgetbytes.com/chorizo-sweet-potato-skillet/',
    name: 'Chorizo sweet potato skillet',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Chorizo', 'Sweet potato'],
  },
  {
    link: 'https://www.bonappetit.com/recipe/corn-and-sausage-pasta?mbid=social_twitter&utm_medium=social&utm_brand=ba&utm_social-type=owned&utm_source=twitter',
    name: 'Corn sausage pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Corn', 'Sausage', 'Pasta'],
  },
  {
    link: 'https://www.recipetineats.com/corn-ribs/',
    name: 'Corn ribs',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Corn'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/creamy-chicken-and-pea-pasta-bake',
    name: 'Creamy chicken pea bake',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Peas', 'Pasta'],
  },
  {
    link: 'https://www.marionskitchen.com/creamy-japanese-potato-salad/',
    name: 'Japanese potato salad',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Potatoes'],
  },
  {
    link: 'https://www.thekitchn.com/miracle-meal-lemon-ricotta-pasta-22956641',
    name: 'Ricotta broccoli pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Ricotta', 'Broccoli', 'Pasta'],
  },
  {
    link: 'https://www.laurainthekitchen.com/recipes/creamy-shells-with-peas-and-prosciutto/',
    name: 'Shells peas prosciutto',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta shells', 'Peas', 'Prosciutto'],
    notes: 'Add another cup of peas',
  },
  {
    link: 'https://www.marionskitchen.com/creamy-roasted-potato-bacon-salad-with-miso-dressing/',
    name: 'Miso potato bacon salad',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Potatoes', 'Bacon'],
  },
  {
    link: 'https://30seconds.com/food/tip/17556/Crispy-Broccoli-Cheese-Balls-Recipe-This-Baked-Appetizer-Recipe-Is-a-Fan-Favorite',
    name: 'Broccoli cheese balls',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Broccoli', 'Cheese'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/279032/crispy-cod-with-charred-snow-peas-creamy-herb-sauce/',
    name: 'Crispy cod snow peas',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Cod', 'Snow peas'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/281051/crispy-fish-taco-bowls/',
    name: 'Crispy fish taco bowls',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Fish'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/crumbed-fish-and-oven-baked-chips',
    name: 'Crumbed fish and chips',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Fish', 'Potatoes'],
  },
  {
    link: 'https://www.kitchensanctuary.com/easy-baked-pesto-chicken/',
    name: 'Baked pesto chicken',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Pesto'],
  },
  {
    link: 'https://www.kitchensanctuary.com/easy-chicken-ramen-ready-in-20-mins/',
    name: 'Easy chicken ramen',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Chicken', 'Ramen noodles'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/easy-chilli-and-garlic-chicken-pasta',
    name: 'Chilli garlic chicken pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Pasta', 'Garlic', 'Chilli'],
  },
  {
    link: 'https://www.youtube.com/watch?v=-XU9gxdAqr0&list=WL&index=6',
    name: 'Japanese egg sandwich',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Eggs', 'Bread'],
    notes: 'Tomatoes instead of olives',
  },
  {
    link: 'https://www.eatingwell.com/recipe/269786/easy-pea-spinach-carbonara/',
    name: 'Pea spinach carbonara',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Peas', 'Spinach', 'Pasta'],
    notes: 'Make our own chicken breast steaks',
  },
  {
    link: 'https://www.recipesmadeeasy.co.uk/easy-oriental-pork/',
    name: 'Pork hokkien noodles',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Pork', 'Hokkien noodles'],
    notes: 'Marinate 1hr with chilli oil, garlic salt and rosemary',
  },
  {
    link: 'https://www.youtube.com/watch?v=2x1M3sYtiE0&list=WL&index=5',
    name: 'Stir fried beef noodles',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef', 'Noodles'],
  },
  {
    link: 'https://mynameisyeh.com/mynameisyeh/2014/8/fettuccine-carbonara-with-green-beans',
    name: 'Carbonara green beans',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Fettuccine', 'Green beans', 'Spinach'],
  },
  {
    link: 'https://www.sobeys.com/en/recipes/fish-au-gratin/',
    name: 'Fish au gratin',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Fish', 'Cheese'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/our-recipe/fish-burgers/',
    name: 'Fish burgers',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Fish'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/fish-fillet-burgers',
    name: 'Fish fillet burgers',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Fish'],
  },
  {
    link: '',
    name: 'Five sauce prawns',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Prawns'],
  },
  {
    link: 'https://www.youtube.com/watch?v=WDNOJ3_j2mM&list=WL&index=2',
    name: 'French onion grilled cheese',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Bread', 'Cheese', 'Onions'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/special-fried-spam-with-rice-noodles',
    name: 'Fried spam rice noodles',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Spam', 'Rice noodles'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/healthier-garlic-beef-and-greens-stir-fry',
    name: 'Garlic beef greens stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef', 'Greens', 'Potatoes'],
  },
  {
    link: 'https://www.cookingclassy.com/garlic-butter-chicken-bites/',
    name: 'Garlic butter chicken bites',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Chicken'],
  },
  {
    link: 'https://www.recipetineats.com/garlic-butter-salmon-recipe/',
    name: 'Garlic butter salmon',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Salmon'],
  },
  {
    link: 'https://www.youtube.com/watch?v=LEFCBr4Woh4&list=WL&index=2',
    name: 'Garlic butter noodles',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Noodles', 'Parmesan'],
  },
  {
    link: 'https://www.marionskitchen.com/garlic-shrimp-hokkien-noodles/',
    name: 'Garlic prawn hokkien noodles',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Prawns', 'Hokkien noodles'],
  },
  {
    link: 'https://www.marionskitchen.com/garlic-prawn-pad-see-ew/',
    name: 'Garlic prawn pad see ew',
    cuisine: 'Thai',
    isFavorite: false,
    ingredients: ['Prawns', 'Rice noodles'],
  },
  {
    link: 'https://www.marionskitchen.com/garlic-shrimp-chilli-oil-noodles/',
    name: 'Garlic shrimp chilli noodles',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Prawns', 'Noodles'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/garlic-bread-toasties',
    name: 'Garlic bread toasties',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Bread', 'Garlic'],
  },
  {
    link: 'https://bakerbynature.com/garlicky-tomato-basil-pasta-salad/',
    name: 'Tomato basil pasta salad',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta', 'Tomatoes', 'Basil'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/gnocchi-with-pesto-and-crispy-chorizo',
    name: 'Gnocchi pesto chorizo',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Gnocchi', 'Pesto', 'Chorizo'],
    notes: 'Replace dry vermouth with balsamic vinegar',
  },
  {
    link: 'https://www.eatingwell.com/recipe/7944667/gochujang-glazed-salmon-with-garlic-spinach/',
    name: 'Gochujang salmon',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Salmon', 'Spinach'],
  },
  {
    link: 'https://www.bonappetit.com/recipe/gochujang-sesame-noodles',
    name: 'Gochujang sesame noodles',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Noodles'],
  },
  {
    link: 'https://www.fifteenspatulas.com/quick-ground-pork-and-tofu-stir-fry/',
    name: 'Ground pork tofu stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Pork', 'Tofu', 'Carrot', 'Rice'],
  },
  {
    link: 'https://www.marionskitchen.com/gyudon-japanese-beef-rice-bowl/',
    name: 'Gyudon beef bowl',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Beef', 'Rice'],
  },
  {
    link: 'https://www.foodandwine.com/recipes/hatch-chile-smash-burgers',
    name: 'Hatch chile smash burgers',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Beef', 'Chiles'],
    notes: 'Mozzarella balls',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/hawaiian-chicken-quesadillas',
    name: 'Hawaiian chicken quesadillas',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Chicken', 'Pineapple'],
    notes: 'Add steak',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/healthier-garlic-chicken-with-pickled-cucumber',
    name: 'Garlic chicken pickled cucumber',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Chicken', 'Cucumber'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/healthier-gozleme-hand-pies',
    name: 'Gozleme hand pies',
    cuisine: 'Turkish',
    isFavorite: false,
    ingredients: ['Pastry'],
    notes: 'Instead of feta grill halloumi. Marinate for 30min',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/healthier-prawn-and-dill-pizza',
    name: 'Prawn dill pizza',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Prawns', 'Dill'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/healthier-pumpkin-and-ricotta-pasta-bake',
    name: 'Pumpkin ricotta pasta bake',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pumpkin', 'Ricotta', 'Pasta'],
    notes: 'Green beans',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/hoisin-pork-and-noodles',
    name: 'Hoisin pork noodles',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Pork', 'Hokkien noodles'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/hoisin-pork-and-vegetable-stir-fry',
    name: 'Hoisin pork veg stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Pork', 'Vegetables'],
  },
  {
    link: '',
    name: 'Hokkien chicken noodles',
    cuisine: 'Malaysian',
    isFavorite: false,
    ingredients: ['Hokkien noodles', 'Chicken', 'Bok choy', 'Cucumber'],
  },
  {
    link: 'https://christieathome.com/blog/kl-hokkien-mee/',
    name: 'Hokkien mee',
    cuisine: 'Malaysian',
    isFavorite: false,
    ingredients: ['Hokkien noodles', 'Prawns', 'Pork mince', 'Asian greens'],
  },
  {
    link: 'https://www.budgetbytes.com/honey-balsamic-carrots/',
    name: 'Honey balsamic carrots',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Carrots'],
  },
  {
    link: 'https://www.delish.com/cooking/recipe-ideas/recipes/a58381/honey-glazed-carrots-recipe/',
    name: 'Honey glazed carrots',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Carrots'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/honey-mustard-meatballs-with-mash',
    name: 'Honey mustard meatballs',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Meatballs', 'Potatoes'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/hot-and-spicy-korean-style-noodles',
    name: 'Spicy Korean noodles',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Noodles'],
  },
  {
    link: 'https://www.nigella.com/recipes/lasagne-of-love',
    name: 'Lasagne',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta sheets', 'Beef'],
  },
  {
    link: 'https://www.deliciousmagazine.co.uk/recipes/leftover-beef-miso-udon/',
    name: 'Beef miso udon',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Beef', 'Udon noodles'],
  },
  {
    link: 'https://hellofresh.com/recipecards/card/lemon-pepper-prawn-chorizo-rolls-6397fd427ae3db9777053b2d-cffde826.pdf',
    name: 'Lemon pepper prawn rolls',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Prawns', 'Chorizo'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/7896459/lemon-garlic-steak-green-beans/',
    name: 'Lemon garlic steak',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Steak', 'Green beans'],
  },
  {
    link: 'https://www.rte.ie/lifestyle/recipes/2021/1014/1253718-donal-skehans-mac-n-peas/',
    name: 'Mac and peas',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Macaroni', 'Peas'],
  },
  {
    link: 'https://www.instagram.com/p/CkZ2IIavtzk/?igshid=MDJmNzVkMjY=',
    name: 'Mango ice cream',
    cuisine: 'Indian',
    isFavorite: false,
    ingredients: ['Mango'],
    notes: 'Cook meat sauce in oven longer',
  },
  {
    link: 'https://everydaygourmet.tv/recipes/mango-meringue-tart',
    name: 'Mango meringue tart',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Mango'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/marry-me-chicken-pasta',
    name: 'Marry me chicken pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Pasta'],
  },
  {
    link: 'https://minimalistbaker.com/fluffy-mashed-sweet-potatoes-and-carrots/',
    name: 'Mashed sweet potato carrots',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Sweet potatoes', 'Carrots'],
  },
  {
    link: 'https://thecookingjar.com/meatball-pasta-bake/',
    name: 'Meatball rigatoni bake',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Meatballs', 'Rigatoni', 'Spinach'],
  },
  {
    link: 'https://www.youtube.com/watch?v=X1D2AUehXao&list=WL&index=3',
    name: 'Meatball sub',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Meatballs', 'Bread'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/mexican-inspired-haloumi-burger',
    name: 'Mexican halloumi burger',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Halloumi'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/our-recipe/mexican-street-corn-salsa-with-seared-salmon/',
    name: 'Mexican corn salmon',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Salmon', 'Corn'],
  },
  {
    link: 'https://www.taste.com.au/recipes/mini-cheese-bacon-sausage-rolls-recipe/syxehhyd',
    name: 'Mini sausage rolls',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Sausage', 'Cheese', 'Bacon', 'Pastry'],
  },
  {
    link: 'https://www.marionskitchen.com/four-cheese-miso-mushroom-pizza/',
    name: 'Miso cheese mushroom pizza',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Cheese', 'Mushrooms'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/mocha-ganache-tarts',
    name: 'Mocha ganache tarts',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Chocolate', 'Coffee'],
  },
  {
    link: 'https://www.budgetbytes.com/monterey-chicken-skillet/',
    name: 'Monterey chicken skillet',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Chicken'],
  },
  {
    link: 'https://www.youtube.com/watch?v=mHqgGHwM0Rc&list=WL&index=2',
    name: 'Nutella mug cake',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Nutella'],
  },
  {
    link: 'https://www.marionskitchen.com/one-pot-honey-soy-chicken-rice/',
    name: 'Honey soy chicken rice',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Chicken', 'Rice'],
  },
  {
    link: 'https://www.taste.com.au/recipes/one-pot-melting-lemon-salmon-spaghetti-recipe/uamo8gd0',
    name: 'Lemon salmon spaghetti',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Salmon', 'Spaghetti'],
  },
  {
    link: 'https://www.marionskitchen.com/one-tray-steamed-soy-ginger-salmon/',
    name: 'Soy ginger salmon',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Salmon'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/one-pan-carbonara',
    name: 'One pan carbonara',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta', 'Bacon', 'Eggs'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/one-pan-spinach-and-ricotta-rotolo',
    name: 'Spinach ricotta rotolo',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Spinach', 'Ricotta', 'Pasta'],
    notes: 'Add chorizo',
  },
  {
    link: 'https://www.eatingwell.com/recipe/7934317/one-pot-chicken-pasta-with-cajun-seasonings/',
    name: 'Cajun chicken pasta',
    cuisine: 'Cajun',
    isFavorite: false,
    ingredients: ['Chicken', 'Pasta'],
    notes: 'X2 options is 450g pasta',
  },
  {
    link: 'https://www.eatingwell.com/recipe/7919492/one-pot-garlicky-shrimp-broccoli/',
    name: 'Garlicky shrimp broccoli',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Shrimp', 'Broccoli'],
    notes: '400g corn',
  },
  {
    link: 'https://www.eatingwell.com/recipe/269496/one-pot-garlicky-shrimp-spinach/',
    name: 'Garlicky shrimp spinach',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Shrimp', 'Spinach'],
  },
  {
    link: '',
    name: 'Vegetarian gnocchi pumpkin',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Gnocchi', 'Pumpkin'],
    notes: 'With meatballs',
  },
  {
    link: '',
    name: 'Open face pastries',
    cuisine: 'Scandinavian',
    isFavorite: false,
    ingredients: ['Pastry', 'Tomato paste', 'Cheese', 'Ham', 'Mushrooms', 'Spinach'],
  },
  {
    link: 'https://www.youtube.com/watch?v=akRsKKwddnU',
    name: 'Pan roasted salmon',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Salmon', 'Potatoes', 'Garlic', 'Herbs', 'Lemon'],
  },
  {
    link: 'https://www.myrecipes.com/recipe/pan-fried-beef-scallion-dumplings',
    name: 'Beef scallion dumplings',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef', 'Scallions'],
    notes: 'Add Parmesan and salt',
  },
  {
    link: 'https://www.recipesmadeeasy.co.uk/easy-oriental-pork/',
    name: 'Pappardelle pork',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Pappardelle', 'Pork', 'Bok choy'],
    notes: 'Pappardelle, bok choy, trio Italian herbs, 1 tsp chilli oil, dark soy, sesame seeds, carrots, spring onions',
  },
  {
    link: 'https://www.goodchefbadchef.com.au/our-recipe/parmesan-cheese-souffle/',
    name: 'Parmesan soufflé',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Parmesan', 'Eggs'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/one-pan-parmesan-crusted-chicken-with-broccoli',
    name: 'Parmesan crusted chicken',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Chicken', 'Broccoli'],
  },
  {
    link: 'https://www.budgetbytes.com/pasta-with-bacon-and-peas/',
    name: 'Pasta bacon peas',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta', 'Bacon', 'Peas'],
  },
  {
    link: '',
    name: 'Pasta chorizo mushrooms',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pasta', 'Pasta sauce', 'Chorizo', 'Mushrooms', 'Corn'],
  },
  {
    link: 'https://www.deliciousmagazine.co.uk/recipes/cheese-bacon-pesto-puffs/',
    name: 'Pastry tarts variety',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Pastry', 'Bocconcini', 'Bacon', 'Pesto', 'Tomato', 'Mushroom', 'Pork'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/pesto-fettuccine',
    name: 'Pesto fettuccine prawns',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Fettuccine', 'Pesto', 'Prawns'],
  },
  {
    link: 'https://www.simplyrecipes.com/pesto-shrimp-with-cherry-tomatoes-recipe-8654920',
    name: 'Pesto shrimp tomatoes',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Shrimp', 'Pesto', 'Cherry tomatoes'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/pork-and-prawn-wontons-with-chilli-oil',
    name: 'Pork prawn wontons',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Pork', 'Prawns'],
  },
  {
    link: 'https://www.bonappetit.com/recipe/pork-and-bok-choy-stir-fry',
    name: 'Pork bok choy stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Pork', 'Bok choy'],
    notes: 'Green peas instead of chickpeas, chilli',
  },
  {
    link: '',
    name: 'Pork ragu',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pork'],
  },
  {
    link: 'https://www.recipetineats.com/san-choy-bow-chinese-lettuce-wraps/',
    name: 'Pork san choy bao',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Pork', 'Lettuce', 'Rice'],
    notes: 'Cream substitute: add ¼ cup of melted butter to ¾ cup full fat milk',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/pork-with-roast-broccolini-and-garlic-potatoes',
    name: 'Pork broccolini potatoes',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Pork', 'Broccolini', 'Potatoes'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/pork-fennel-and-pea-gnocchi',
    name: 'Pork fennel pea gnocchi',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Pork', 'Fennel', 'Peas', 'Gnocchi'],
  },
  {
    link: 'https://www.budgetbytes.com/potato-and-green-bean-skillet/',
    name: 'Potato green bean skillet',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Potatoes', 'Green beans'],
  },
  {
    link: 'https://www.recipetineats.com/potatoes-au-gratin/',
    name: 'Potatoes au gratin',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Potatoes'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/our-recipe/prawn-and-spinach-dumplings/',
    name: 'Prawn spinach dumplings',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Prawns', 'Spinach'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/prawn-spring-rolls-with-sweet-chilli-lime-mayo',
    name: 'Prawn spring rolls',
    cuisine: 'Vietnamese',
    isFavorite: false,
    ingredients: ['Prawns'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/prawn-and-leek-stir-fry',
    name: 'Prawn leek stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Prawns', 'Leeks'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/quick-dumpling-and-greens-stir-fry',
    name: 'Dumpling greens stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Dumplings', 'Greens'],
  },
  {
    link: 'https://www.hellofresh.com/recipecards/card/quick-soy-ginger-beef-6397dd30beb8c682b50863e6-981d4cc9.pdf',
    name: 'Soy ginger beef',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Beef'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/quick-sticky-salmon-with-rice-and-salad',
    name: 'Sticky salmon bowl',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice', 'Bok choy', 'Egg'],
  },
  {
    link: 'https://www.epicurious.com/recipes/food/views/red-pesto-rigatoni-pasta',
    name: 'Red pesto rigatoni',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Rigatoni', 'Red pesto'],
  },
  {
    link: 'https://www.marionskitchen.com/rice-cooker-garlic-prawn-rice/',
    name: 'Rice cooker prawn rice',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Prawns', 'Rice'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/special-fried-spam-with-rice-noodles',
    name: 'Rice noodles spam chicken',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Rice noodles', 'Spam', 'Chicken', 'Chinese sausage'],
  },
  {
    link: 'https://www.howsweeteats.com/2021/10/ricotta-pasta/',
    name: 'Ricotta roasted broccoli pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Ricotta', 'Broccoli', 'Pasta'],
    notes: 'Add sautéed spinach and mushrooms',
  },
  {
    link: 'http://healthyhomecafe.com/2016/12/16/roasted-pumpkin-salad/',
    name: 'Roast pumpkin salad',
    cuisine: 'Mediterranean',
    isFavorite: false,
    ingredients: ['Pumpkin'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/7870123/salmon-avocado-salad/',
    name: 'Salmon avocado salad',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Salmon', 'Avocado'],
  },
  {
    link: 'https://www.smh.com.au/goodfood/recipes/recipetin-s-rice-bowls-stretch-two-salmon-fillets-into-a-satisfying-dinner-for-four-20240507-p5fpjt.html',
    name: 'Salmon bowl',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice'],
  },
  {
    link: 'https://www.epicurious.com/recipes/food/views/salmon-croquettes-dill-sauce',
    name: 'Salmon croquettes',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Salmon'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/salmon-donburi',
    name: 'Salmon donburi',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice'],
    notes: 'Replace capsicum with carrot',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/salmon-pasta-bake',
    name: 'Salmon pasta bake',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Salmon', 'Pasta'],
    notes: 'Replace cooking sake with xiaosing wine',
  },
  {
    link: 'https://www.goodchefbadchef.com.au/our-recipe/salmon-rainbow-poke-bowl/',
    name: 'Salmon rainbow poke bowl',
    cuisine: 'Hawaiian',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice'],
  },
  {
    link: 'https://www.howsweeteats.com/2018/04/salmon-rice-bowls/',
    name: 'Salmon rice bowls',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice'],
  },
  {
    link: 'https://www.youtube.com/shorts/DZyEwuGHpHQ',
    name: 'Salmon bok choy edamame bowl',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice', 'Bok choy', 'Edamame'],
    notes: '2 tbsp soy sauce, 1 tbsp oyster sauce, 1 tbsp sesame oil. Add cucumber, avocado, kewpie, sriracha, green onions, seaweed',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/tasty-pastry-twists',
    name: 'Sausage cheese pastry twists',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Sausage', 'Cheese', 'Pastry'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/quick-sausage-and-pesto-pasta',
    name: 'Sausage pesto pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Sausage', 'Pesto', 'Pasta'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/sausage-enchiladas-with-tomato-salad',
    name: 'Sausage enchiladas',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Sausage'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/sausage-pappardelle-with-rosemary-panko-crumb',
    name: 'Sausage pappardelle',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Sausage', 'Pappardelle'],
  },
  {
    link: 'https://www.cookingclassy.com/skillet-garlic-parmesan-zucchini-squash-tomatoes/',
    name: 'Garlic parmesan zucchini',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Zucchini', 'Squash', 'Tomatoes'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/scotch-fillet-with-french-shallot-sauce',
    name: 'Scotch fillet shallot sauce',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Beef', 'Shallots'],
  },
  {
    link: 'https://www.seriouseats.com/chinese-tomato-scrambled-egg-recipe-5218069',
    name: 'Scrambled eggs tomatoes',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Eggs', 'Tomatoes'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/sesame-beef-rice-bowls',
    name: 'Sesame beef udon bowls',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Beef', 'Udon noodles'],
  },
  {
    link: 'https://www.budgetbytes.com/easy-sesame-chicken/',
    name: 'Sesame chicken',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Chicken'],
  },
  {
    link: 'https://www.delicious.com.au/recipes/sesame-crumbed-pork-cutlets-quick-tonkatsu-sauce/59d8cf23-2428-40f4-9b02-49d9be71826f',
    name: 'Sesame pork cutlets',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Pork'],
    notes: 'Marinade beef for 30 minutes (needs more flavour)',
  },
  {
    link: 'https://www.eatingwell.com/recipe/7959062/sheet-pan-shrimp-fajitas/',
    name: 'Sheet pan shrimp fajitas',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Shrimp'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/shredded-chicken-nachos',
    name: 'Shredded chicken nachos',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Chicken'],
  },
  {
    link: '',
    name: 'Shrimp mushroom stir fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Shrimp', 'Mushrooms'],
  },
  {
    link: 'https://www.bonappetit.com/recipe/shrimp-and-salami-pasta',
    name: 'Shrimp salami pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Shrimp', 'Salami', 'Pasta'],
    notes: "Don't add sugar",
  },
  {
    link: 'https://www.foodandwine.com/recipes/shrimp-burgers',
    name: 'Shrimp burgers',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Shrimp'],
  },
  {
    link: 'https://www.foodandwine.com/recipes/shrimp-cakes',
    name: 'Shrimp cakes',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Shrimp'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/265720/shrimp-poke/',
    name: 'Shrimp poke',
    cuisine: 'Hawaiian',
    isFavorite: false,
    ingredients: ['Shrimp'],
  },
  {
    link: 'https://www.marionskitchen.com/korean-style-shrimp-scampi-spaghetti/',
    name: 'Shrimp scampi spaghetti',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Shrimp', 'Spaghetti'],
  },
  {
    link: 'https://www.youtube.com/watch?v=ij4XIP1TUOA&list=WL&index=2',
    name: 'Shrimp tacos',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Shrimp'],
  },
  {
    link: 'https://www.cookerru.com/yaki-udon-noodles/',
    name: 'Shrimp yaki udon',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Shrimp', 'Udon noodles'],
  },
  {
    link: 'https://www.foodandwine.com/recipes/shrimp-and-pork-pan-fried-noodles',
    name: 'Shrimp pork fried noodles',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Shrimp', 'Pork', 'Noodles'],
  },
  {
    link: 'https://tasty.co/article/hannahmars/easy-fettuccine',
    name: 'Shrimp tomato spinach pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Shrimp', 'Tomato', 'Spinach', 'Pasta'],
  },
  {
    link: 'https://www.donnahay.com.au/recipes/dinner/pasta-and-noodles/silky-miso-pasta',
    name: 'Silky miso pasta chorizo',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Pasta', 'Chorizo'],
  },
  {
    link: 'https://www.youtube.com/watch?v=s_MJDsGuzc4&list=WL&index=4',
    name: 'Single serve choc chip cookie',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Chocolate chips'],
  },
  {
    link: 'https://www.deliciousmagazine.co.uk/recipes/slow-baked-meatballs/',
    name: 'Slow baked meatballs',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Meatballs'],
  },
  {
    link: 'https://simplehomeedit.com/recipe/slow-cooked-beef-ragu/',
    name: 'Slow cooked beef ragu',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Beef'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/slow-cooked-pork-tacos-with-avocado-salsa',
    name: 'Slow cooked pork tacos',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Pork', 'Avocado'],
    notes: '1 less tbsp of chilli',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/smoked-salmon-french-toast',
    name: 'Smoked salmon french toast',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Salmon', 'Bread'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/257109/smoky-shrimp-corn-pea-one-pot-pasta/',
    name: 'Smoky shrimp corn pea pasta',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Shrimp', 'Corn', 'Peas', 'Pasta'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/speedy-chicken-ginger-and-sweet-corn-soup',
    name: 'Chicken ginger corn soup',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Chicken', 'Corn', 'Ginger'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/speedy-chorizo-and-chicken-rice',
    name: 'Chorizo chicken rice',
    cuisine: 'Spanish',
    isFavorite: false,
    ingredients: ['Chorizo', 'Chicken', 'Rice'],
    notes: 'Red wine substitute with chick stock. 3/4 chilli flakes',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/speedy-laksa',
    name: 'Speedy laksa',
    cuisine: 'Malaysian',
    isFavorite: false,
    ingredients: ['Noodles'],
  },
  {
    link: 'https://www.jamieoliver.com/recipes/prawn/spiced-prawn-flatbreads',
    name: 'Spiced prawn flatbreads',
    cuisine: 'Middle Eastern',
    isFavorite: false,
    ingredients: ['Prawns', 'Flatbread'],
  },
  {
    link: 'https://www.youtube.com/watch?v=rHMq7rcrtqs&list=WL&index=3',
    name: 'Gochujang beef udon',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Beef', 'Udon noodles'],
  },
  {
    link: 'https://www.marionskitchen.com/spicy-korean-pork-stir-fry/',
    name: 'Spicy Korean pork stir fry',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Pork'],
  },
  {
    link: 'https://www.marionskitchen.com/spicy-meatball-banh-mi/',
    name: 'Spicy meatball banh mi',
    cuisine: 'Vietnamese',
    isFavorite: false,
    ingredients: ['Meatballs'],
  },
  {
    link: 'https://www.bonappetit.com/recipe/spicy-pork-bowl-with-greens-and-carrots',
    name: 'Spicy pork bowl',
    cuisine: 'Korean',
    isFavorite: false,
    ingredients: ['Pork', 'Greens', 'Carrots'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/spicy-salmon-sushi-rolls',
    name: 'Spicy salmon sushi rolls',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice'],
  },
  {
    link: 'https://www.marionskitchen.com/spicy-wonton-noodle-soup/',
    name: 'Spicy wonton noodle soup',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Wontons', 'Noodles'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/spinach-ricotta-and-tomato-toastie',
    name: 'Spinach ricotta toastie',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Spinach', 'Ricotta', 'Tomato'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/spring-roll-noodle-salad-bun-cha-gio',
    name: 'Spring roll noodle salad',
    cuisine: 'Vietnamese',
    isFavorite: false,
    ingredients: ['Spring rolls', 'Noodles'],
  },
  {
    link: 'https://www.youtube.com/watch?v=h9tTqrW1WMc',
    name: 'Steak',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Steak'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/steak-with-dijon-sauce',
    name: 'Steak dijon sauce',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Steak'],
  },
  {
    link: 'https://www.marionskitchen.com/sticky-chilli-ginger-salmon/',
    name: 'Sticky chilli ginger salmon',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Salmon'],
  },
  {
    link: 'https://cooking.nytimes.com/recipes/1025510-sticky-miso-salmon-bowl',
    name: 'Sticky miso salmon bowl',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Salmon', 'Rice'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/sticky-date-mug-cakes',
    name: 'Sticky date mug cakes',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Dates'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/vegetarian-stir-fried-drunken-noodles',
    name: 'Stir fry noodles lap cheong',
    cuisine: 'Thai',
    isFavorite: false,
    ingredients: ['Noodles', 'Lap cheong'],
  },
  {
    link: 'https://www.jamieoliver.com/recipes/ice-cream-recipes/no-churn-strawberry-ripple-ice-cream/',
    name: 'Strawberry ripple ice cream',
    cuisine: 'British',
    isFavorite: false,
    ingredients: ['Strawberries'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/stuffed-mushroom-toasties',
    name: 'Stuffed mushroom toasties',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Mushrooms', 'Bread'],
  },
  {
    link: 'https://www.eatingwell.com/recipe/250521/summer-corn-scallop-pasta/',
    name: 'Summer corn scallop pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Corn', 'Scallops', 'Pasta'],
  },
  {
    link: 'https://giadzy.com/recipes/summer-corn-and-spicy-sausage-pizza/',
    name: 'Corn spicy sausage pizza',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Corn', 'Sausage'],
  },
  {
    link: 'https://www.youtube.com/watch?v=2n0kEt6VLNg',
    name: 'Sushi bake',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Salmon', 'Crab', 'Rice'],
  },
  {
    link: 'https://www.delish.com/cooking/recipe-ideas/recipes/a50808/sushi-bowls-recipe/',
    name: 'Sushi bowls',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Rice', 'Fish'],
  },
  {
    link: 'https://everydaygourmet.tv/recipes/sweet-and-sour-prawns',
    name: 'Sweet and sour prawns',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Prawns'],
    notes: 'Ricotta instead of goat cheese. Spinach instead of rocket. Breadcrumbs and parmesan on top for crunch',
  },
  {
    link: 'https://www.woolworths.com.au/shop/meal-plan?recipeId=sweet-chilli-and-garlic-pork-pappardelle',
    name: 'Sweet chilli garlic pork pasta',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Pork', 'Pappardelle'],
  },
  {
    link: 'https://www.nigella.com/recipes/sweet-potato-macaroni-cheese',
    name: 'Sweet potato mac cheese',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Sweet potato', 'Macaroni'],
  },
  {
    link: 'https://feelgoodfoodie.net/recipe/ground-beef-tacos-napa-cabbage-guacamole/',
    name: 'Beef tacos guacamole',
    cuisine: 'Mexican',
    isFavorite: false,
    ingredients: ['Beef', 'Guacamole'],
  },
  {
    link: 'https://www.youtube.com/watch?v=oalZ1Y1VAE4',
    name: 'Teriyaki cheesesteak',
    cuisine: 'Fusion',
    isFavorite: false,
    ingredients: ['Beef', 'Cheese'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/teriyaki-chicken-sushi-salad',
    name: 'Teriyaki chicken sushi salad',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Chicken', 'Rice'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/teriyaki-pork-meatballs-with-sesame-and-ginger-veg',
    name: 'Teriyaki pork meatballs',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Pork', 'Meatballs'],
  },
  {
    link: 'https://www.youtube.com/watch?v=AYXfaVD5o40',
    name: 'Teriyaki salmon skewers',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Salmon'],
  },
  {
    link: 'https://www.delicious.com.au/recipes/teriyaki-salmon-udon-noodles-recipe/yo2a9x4c',
    name: 'Teriyaki salmon udon',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Salmon', 'Udon noodles'],
  },
  {
    link: 'https://www.epicurious.com/recipes/food/views/teriyaki-steak-skewers-with-asian-style-greens',
    name: 'Teriyaki steak skewers',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Steak'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/tikka-fish-with-naan-fattoush',
    name: 'Tikka fish naan fattoush',
    cuisine: 'Indian',
    isFavorite: false,
    ingredients: ['Fish', 'Naan'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/toasted-bacon-and-cheese-wrap',
    name: 'Bacon cheese wrap',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Bacon', 'Cheese'],
  },
  {
    link: 'https://www.youtube.com/watch?v=jWR8OCxAvg0',
    name: 'Tomato cheese tarts',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Tomatoes', 'Cheese', 'Pastry'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/tomato-and-cheese-tarts',
    name: 'Tomato cheese tarts',
    cuisine: 'French',
    isFavorite: false,
    ingredients: ['Tomatoes', 'Cheese'],
  },
  {
    link: 'https://thewoksoflife.com/stir-fried-tomato-and-egg/',
    name: 'Tomato egg fry',
    cuisine: 'Chinese',
    isFavorite: false,
    ingredients: ['Tomatoes', 'Eggs'],
  },
  {
    link: 'https://tasty.co/article/hannahmars/easy-fettuccine',
    name: 'Tomato broccoli pesto pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Tomatoes', 'Broccoli', 'Pesto', 'Pasta'],
  },
  {
    link: 'https://www.donnahay.com.au/recipes/dinner/pizza/tomato-chorizo-and-zucchini-cheats-pizza',
    name: 'Tomato chorizo zucchini pizza',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Tomatoes', 'Chorizo', 'Zucchini'],
  },
  {
    link: 'https://www.taste.com.au/recipes/creamy-tuna-pasta/630611c8-4995-41cc-9f07-6c56c42267eb',
    name: 'Creamy tuna pasta',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Tuna', 'Pasta'],
    notes: 'White sauce instead of cream',
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/tuna-primavera',
    name: 'Tuna primavera',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Tuna', 'Pasta'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/tuna-melt-toastie',
    name: 'Tuna melt toastie',
    cuisine: 'American',
    isFavorite: false,
    ingredients: ['Tuna', 'Cheese'],
  },
  {
    link: 'https://www.thekitchn.com/tuscan-tortellini-pasta-260311',
    name: 'Tuscan tortellini',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Tortellini'],
  },
  {
    link: 'https://www.eatingwell.com/udon-noodle-soup-with-buttery-tomato-broth-8385774',
    name: 'Udon tomato broth soup',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Udon noodles', 'Tomatoes'],
  },
  {
    link: 'https://www.wandercooks.com/udon-noodle-soup-recipe/',
    name: 'Udon curry soup',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Udon noodles', 'Curry', 'Fish balls', 'Asian greens', 'Corn'],
    notes: '940ml chicken stock, 250g udon, green beans cut into rounds',
  },
  {
    link: '',
    name: 'Udon lap cheung',
    cuisine: 'Malaysian',
    isFavorite: false,
    ingredients: ['Udon', 'Lap cheong', 'Peas', 'Corn', 'Spring onions'],
  },
  {
    link: 'https://tasty.co/recipe/veggie-garlic-noodles',
    name: 'Veggie garlic noodles',
    cuisine: 'Asian Fusion',
    isFavorite: false,
    ingredients: ['Noodles', 'Vegetables', 'Beef mince'],
  },
  {
    link: 'https://www.youtube.com/watch?v=jWR8OCxAvg0',
    name: 'Veggie teriyaki',
    cuisine: 'Japanese',
    isFavorite: false,
    ingredients: ['Vegetables'],
  },
  {
    link: 'https://www.goodchefbadchef.com.au/recipes/vietnamese-meatballs',
    name: 'Vietnamese meatballs',
    cuisine: 'Vietnamese',
    isFavorite: false,
    ingredients: ['Meatballs'],
  },
  {
    link: 'https://www.woolworths.com.au/shop/recipes/vietnamese-style-pancakes',
    name: 'Vietnamese pancakes',
    cuisine: 'Vietnamese',
    isFavorite: false,
    ingredients: ['Rice flour'],
  },
  {
    link: 'https://tasty.co/recipe/zucchini-noodle-chicken-alfredo',
    name: 'Zucchini noodle chicken alfredo',
    cuisine: 'Italian',
    isFavorite: false,
    ingredients: ['Zucchini', 'Chicken'],
  },
]

/**
 * Clear all recipes from the database
 */
export const clearRecipes = mutation({
  handler: async (ctx) => {
    const recipes = await ctx.db.query('recipes').collect()
    for (const recipe of recipes) {
      await ctx.db.delete(recipe._id)
    }
    return {
      success: true,
      deleted: recipes.length,
      message: `Deleted ${recipes.length} recipes`,
    }
  },
})

/**
 * Seed the recipes table with favorite meals from the CSV
 * Run this via the Convex dashboard or CLI to initialize the database
 */
export const seedRecipes = mutation({
  handler: async (ctx) => {
    // Insert seed recipes
    const insertedIds = []
    for (const recipe of SEED_RECIPES) {
      const id = await ctx.db.insert('recipes', {
        link: recipe.link,
        name: recipe.name,
        cuisine: recipe.cuisine,
        isFavorite: recipe.isFavorite,
        ingredients: recipe.ingredients,
        notes: recipe.notes,
      })
      insertedIds.push(id)
    }

    return {
      success: true,
      count: insertedIds.length,
      message: `Seeded ${insertedIds.length} recipes`,
    }
  },
})
