/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RestaurantsRestaurantIdRouteImport } from './routes/restaurants/$restaurantId'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRestaurantIdRoute = RestaurantsRestaurantIdRouteImport.update({
  id: '/restaurants/$restaurantId',
  path: '/restaurants/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
  '/recipes': typeof RecipesIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
  '/recipes': typeof RecipesIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/restaurants/$restaurantId': typeof RestaurantsRestaurantIdRoute
  '/recipes/': typeof RecipesIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/$recipeId'
    | '/restaurants/$restaurantId'
    | '/recipes'
    | '/restaurants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipes/$recipeId'
    | '/restaurants/$restaurantId'
    | '/recipes'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/recipes/$recipeId'
    | '/restaurants/$restaurantId'
    | '/recipes/'
    | '/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RestaurantsRestaurantIdRoute: typeof RestaurantsRestaurantIdRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restaurantId': {
      id: '/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/restaurants/$restaurantId'
      preLoaderRoute: typeof RestaurantsRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RestaurantsRestaurantIdRoute: RestaurantsRestaurantIdRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
